### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by deshack** [deshack/pinit#10]
`readme.txt` is required by WordPress, but not rendered by GitHub. In order to improve the plugin presentation on GitHub too, we should create a README.md.

**Comment by EugenioPetulla** [comment]
My suggestion is to setup a good and catchy WordPress readme and after convert it using this elegant tool: https://github.com/benbalter/WP-Readme-to-Github-Markdown

:)

**Comment by deshack** [comment]
I didn't remember about this tool, but it's good for me.

**Comment by EugenioPetulla** [comment]
Done! Let's have a check if this solution it's good for you but personally I really love it! One click and it's all ready.

I found also a Sublime Text extension that could be ported everywhere because is written in Py (I tried also using it in geany and it worked well too). Give it a try: https://github.com/claudiosmweb/wordpress-readme-to-markdown

**Comment by EugenioPetulla** [comment]
README.md provided with commit: 239135a545105639e01d270503f7ab81e76d0898
