### ISSUE TITLE
Automatically pin new posts

### ISSUE THREAD

**Issue by deshack** [deshack/pinit#9]
[Stefano Agnelli on Wordpress Italy+](https://plus.google.com/+StefanoAgnelli/posts/3ExoVg4LX8j) was in search of a way of automatically post new posts to Pinterest.

Apparently this [is possible](http://codecanyon.net/item/pinterest-automatic-pin-wordpress-plugin/2203314), so why not?

@EugenioPetulla may we discuss about that?

**Comment by EugenioPetulla** [comment]
Actually this is not possibile to do for free beacause Pinterest do not offer a public and free/limitless writing API and doesn't offer a "write to profile" API at all. Every plugin I found use SNAP's private APIs but this is not for free, as you can see from the panel of the plugin you lineked to me from codecanyon: http://i.wpne.ws/dwzp

I'm not sure Pinterest will release a free API because selling access to their services is a business for them and they don't want be the new Twitter: a lot open but a lot in financial trouble! :D

**Comment by deshack** [comment]
Ok, got it. Sad but true :)
